### ISSUE TITLE
“filename” attribute can’t handle double-quotes or UTF-8

### ISSUE THREAD

**Issue by FGasper** [rjbs/Email-MIME#18]
If you do:

``` perl
        Email::MIME->create(
            attributes => {
                'Content-Type' => 'application/octet-string',
                encoding => 'base64',
                disposition => 'attachment',
                filename => 'hah"ha"\'ha\\',
            },
            body => 'This is my “attachment”.',
        ),
```

… Email::MIME does not correctly escape the double quote.

**Comment by labrown** [comment]
This appears to be a specific instance of a more general problem:  The value in the filename attribute should be either a token or a quoted-string (per RFC2045).  Email::Simple, which handles setting the filename attribute in the object, needs to encode the filename value as a quoted-string.

**Comment by karel-m** [comment]
The situation with UTF8 in filenames is even more ... well ... complicated.

Try to run this sample script where I try to encode name/filename manually:

```perl
use Email::MIME;
use Encode 'encode';
use utf8;

print Email::MIME->create(
    attributes => {
      disposition  => 'attachment',
      encoding     => 'base64',
      filename     => encode("MIME-Q", "kůň.pdf"),
      content_type => 'application/pdf',
      name         => encode("MIME-Q", "kůň.pdf"),
    },
    body => 'XXXX',
)->as_string;
```
On my perl 5.22.2 + Encode-2.84 + Email::MIME-1.937 **it gives different results if I execute the script above repeatedly**:

```
Content-Type: application/pdf; name="kůň.pdf"
Content-Disposition: attachment; filename="kůň.pdf"

... in the next run:
Content-Type: application/pdf; name="=?UTF-8?Q?k=C5=AF=C5=88=2Epdf?="
Content-Disposition: attachment; filename="kůň.pdf"

... in the next run (this one is IMO correct/expected):
Content-Type: application/pdf; name="=?UTF-8?Q?k=C5=AF=C5=88=2Epdf?="
Content-Disposition: attachment; filename="=?UTF-8?Q?k=C5=AF=C5=88=2Epdf?="

... in the next run:
Content-Type: application/pdf; name="kůň.pdf"
Content-Disposition: attachment; filename="=?UTF-8?Q?k=C5=AF=C5=88=2Epdf?="

... and so on
```
Any ideas?

**Comment by FGasper** [comment]
Not off-hand, though I can reproduce the behavior. If there’s time tonight I’ll try and dig.

**Comment by FGasper** [comment]
```
  for my $key (keys %attrs) {
    $email->content_type_attribute_set($key => $attrs{$key});
  }
```
^^ It happens because of the unpredictable order here. Looks like content_type needs to be processed first?

**Comment by rjbs** [comment]
I'm afraid I don't think any of the forms given as correct is actually correct.  The correct encoding of Content-Disposition parameters has a long and storied history, but as far as I know the actual encoding is like this:

    Content-Disposition: attachment; filename*utf-8'en-us'This%20is%20encoded

Sorry to be the bearer of bad news. 😉

I agree that this should be fixed, however.

**Comment by pali** [comment]
Right, filename can contains only US-ASCII. filename* could have specified UTF-8 encoding and then we can represent Unicode chars like 😉.

So ideal solution would be to generate both filename* and filename. Put Unicode version into filename* and convert Unicode to ASCII and put it into filename... (as compatibility for email clients which do not support filename*)

**Comment by pali** [comment]
Implemented in PR https://github.com/rjbs/Email-MIME-ContentType/pull/11 and fix for Email::MIME in PR https://github.com/rjbs/Email-MIME/pull/51

**Comment by dxdc** [comment]
Just reviewing old notes. I've experienced this issue before too, just like @FGasper. This was my (hack) work-around at the time, it's because Perl hashes [do not retain their order](https://stackoverflow.com/questions/2011342/what-decides-the-order-of-keys-when-i-print-a-perl-hash).

Is this needed with the new fixes @pali ?

```
  for my $key (sort keys %attrs) {
    $email->content_type_attribute_set($key => $attrs{$key});
  }
```

**Comment by pali** [comment]
@dxdc Attributes in build_content_type are processed in predicable order, see:
https://github.com/rjbs/Email-MIME-ContentType/pull/11/files#diff-0a541362d0d3d73cec199996ecec4272R214
So your change should not be needed.

**Comment by dxdc** [comment]
Thanks @pali you are correct, appreciate the explanation.

**Comment by squm** [comment]
`Email::MIME->new($message)
Missing semicolon before parameter`
