### ISSUE TITLE
Unquoted = not allowed in Content-Type! at /usr/local/share/perl/5.14.2/Email/MIME.pm line 123

### ISSUE THREAD

**Issue by myzinsky** [rjbs/Email-MIME#19]
I want to use Email::MIME::Attachment::Stripper to remove attachments of an E-Mail.

This is the error:
```bash
Unquoted = not allowed in Content-Type! at /usr/local/share/perl/5.14.2/Email/MIME.pm line 123
Illegal Content-Type parameter =_134993AC-C12E-408F-97FA-5C77A36BC897 at /usr/local/share/perl/5.14.2/Email/MIME.pm line 123
Email::MIME=HASH(0x15cecb0)
```

The error occurs when I use this email:
```email
From: Matthias Jung <matthias@jung.ms>
Content-Type: multipart/mixed;
        boundary="Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897"
X-Smtp-Server: smtp.uni-kl.de:jungma@rhrk.uni-kl.de
Date: Wed, 26 Nov 2014 13:59:32 +0100
Subject: testbetreff
X-Universally-Unique-Identifier: B7B0431C-62FD-4826-862F-E936D9CFDAC8
Bcc: Matthias Jung <matthias@jung.ms>
To: spam@jung.ms
Message-Id: <EDFD8C9F-FAB9-4413-8921-1BDA444108FE@jung.ms>
Mime-Version: 1.0 (Mac OS X Mail 8.1 \(1993\))


--Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
        charset=us-ascii

testtext test test test test
test test test test test test test test test test

--Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
Content-Disposition: attachment;
        filename=eicar.zip
Content-Type: application/zip;
        name="eicar.zip"
Content-Transfer-Encoding: base64

UEsDBAoAAAAAAGQ7WyUjS4psRgAAAEYAAAAJAAAAZWljYXIuY29tWDVPIVAlQEFQWzRcUFpYNTQo
UF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCoNClBLAQIU
AAoAAAAAAGQ7WyUjS4psRgAAAEYAAAAJAAAAAAAAAAEAIAD/gQAAAABlaWNhci5jb21QSwUGAAAA
AAEAAQA3AAAAbQAAAAAA
--Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
        charset=us-ascii



--Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897--
```

I used the latest version from CPAN.

Regards
Matthias

**Comment by labrown** [comment]
Went to work on this and am unable to duplicate the error using this script with the current versions of the Email::MIME::* modules on CPAN.

    #!/usr/bin/env perl
    
    use strict;
    use warnings;
    use Email::MIME::Attachment::Stripper;
    
    my $s = Email::MIME::Attachment::Stripper->new(<DATA>);
    my $m = $s->message;
    my @a = $s->attachments;
    print $m->debug_structure;
    
    print $m->as_string;
    
    
    __DATA__
    From: Matthias Jung <matthias@jung.ms>
    Content-Type: multipart/mixed;
            boundary="Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897"
    X-Smtp-Server: smtp.uni-kl.de:jungma@rhrk.uni-kl.de
    Date: Wed, 26 Nov 2014 13:59:32 +0100
    Subject: testbetreff
    X-Universally-Unique-Identifier: B7B0431C-62FD-4826-862F-E936D9CFDAC8
    Bcc: Matthias Jung <matthias@jung.ms>
    To: spam@jung.ms
    Message-Id: <EDFD8C9F-FAB9-4413-8921-1BDA444108FE@jung.ms>
    Mime-Version: 1.0 (Mac OS X Mail 8.1 \(1993\))
    
    
    --Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
    Content-Transfer-Encoding: 7bit
    Content-Type: text/plain;
            charset=us-ascii
    
    testtext test test test test
    test test test test test test test test test test
    
    --Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
    Content-Disposition: attachment;
            filename=eicar.zip
    Content-Type: application/zip;
            name="eicar.zip"
    Content-Transfer-Encoding: base64
    
    UEsDBAoAAAAAAGQ7WyUjS4psRgAAAEYAAAAJAAAAZWljYXIuY29tWDVPIVAlQEFQWzRcUFpYNTQo
    UF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCoNClBLAQIU
    AAoAAAAAAGQ7WyUjS4psRgAAAEYAAAAJAAAAAAAAAAEAIAD/gQAAAABlaWNhci5jb21QSwUGAAAA
    AAEAAQA3AAAAbQAAAAAA
    --Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897
    Content-Transfer-Encoding: 7bit
    Content-Type: text/plain;
            charset=us-ascii
    
    
    
    --Apple-Mail=_134993AC-C12E-408F-97FA-5C77A36BC897--

**Comment by rjbs** [comment]
I'm closing this as un-reproduce-able.

I don't think the script that @labrown gave is quite right.  It calls `Stripper->new(<DATA>)`, which will call getline in list context, etc.

On the other hand, when I read the whole message into a string, make an Email::MIME from that… no problems.

If this can be reproduced and I missed it, please provide a patch with a test or failing script?  Thanks.
