### ISSUE TITLE
Email::MIME defaults to "us-ascii" encoding if only 1 part supplied

### ISSUE THREAD

**Issue by techouse** [rjbs/Email-MIME#22]
Hey! 

I've noticed that `Email::MIME` defaults the `charset` attribute to *us-ascii* if the `parts` list has only 1 element even though that element's `charset` is explicitly set to something other than *us-ascii*, e.g. *UTF-8*. 

Example:

```perl
#!/usr/bin/perl
use warnings;
use strict;
use Email::MIME;

my $email = Email::MIME->create(
    header_str => [
        From => qq{"Your name" <your_email\@some-domain.com>},
        To => qq{"The recipients's name" <recipients_email\@some-domain.com>},
        Subject => qq{Lorem ipsum dolor}
    ],
    parts => [
        Email::MIME->create(
            attributes => {
                encoding => 'quoted-printable',
                content_type => 'text/plain',
                charset => 'UTF-8'
            },
            body_str => qq{Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies condimentum felis, eu auctor ex mattis eu. Ut at diam et tortor imperdiet fringilla. Mauris hendrerit consequat erat, feugiat condimentum dolor pellentesque in. Curabitur eleifend ornare luctus. Vestibulum eget venenatis metus. Sed at nisl vel dui vestibulum semper nec sed turpis. Nunc ultricies volutpat erat a tempus. Praesent ut dui vel erat blandit tempus id nec sem. Nulla sollicitudin non ex at commodo. Aliquam tempor nunc eget consequat commodo. Donec hendrerit posuere velit et feugiat. Integer vel magna a nulla pellentesque consequat. Mauris vestibulum consectetur quam, vitae fermentum ante cursus sit amet. Sed at elit dignissim, euismod velit non, fermentum nisl.}
        )
    ]
);

print $email->as_string;
```

Here's the output:

	From: "Your name" <your_email@some-domain.com>
	To: "The recipients's name" <recipients_email@some-domain.com>
	Subject: Lorem ipsum dolor
	Date: Tue, 17 Mar 2015 11:21:16 +0100
	MIME-Version: 1.0
	Content-Transfer-Encoding: quoted-printable
	Content-Type: text/plain; charset="us-ascii"

	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultricies cond=
	imentum felis, eu auctor ex mattis eu. Ut at diam et tortor imperdiet fring=
	illa. Mauris hendrerit consequat erat, feugiat condimentum dolor pellentesq=
	ue in. Curabitur eleifend ornare luctus. Vestibulum eget venenatis metus. S=
	ed at nisl vel dui vestibulum semper nec sed turpis. Nunc ultricies volutpa=
	t erat a tempus. Praesent ut dui vel erat blandit tempus id nec sem. Nulla =
	sollicitudin non ex at commodo. Aliquam tempor nunc eget consequat commodo.=
	 Donec hendrerit posuere velit et feugiat. Integer vel magna a nulla pellen=
	tesque consequat. Mauris vestibulum consectetur quam, vitae fermentum ante =
	cursus sit amet. Sed at elit dignissim, euismod velit non, fermentum nisl.=

The problem goes away as soon as the `parts` list has more than 1 element.

I'm using version 1.929

	cpan -D Email::MIME
	Reading '/root/.cpan/Metadata'
	  Database was generated on Sun, 15 Mar 2015 10:53:29 GMT
	Email::MIME
	-------------------------------------------------------------------------
			(no description)
			R/RJ/RJBS/Email-MIME-1.929.tar.gz
			/usr/local/share/perl/5.14.2/Email/MIME.pm
			Installed: 1.929
			CPAN:      1.929  up to date
			Ricardo SIGNES (RJBS)
			rjbs@cpan.org

**Comment by rjbs** [comment]
I've uploaded Email-MIME-1.931-TRIAL and will make it a stable release in 2wk if all goes well.

**Comment by techouse** [comment]
Nice! Thanx! :+1:
