### ISSUE TITLE
implement header_str

### ISSUE THREAD

**Issue by mbunkus** [rjbs/Email-MIME#23]
Hey,

it's nice that you've implemented `header_str_pairs`. Please also implement `header_str` which would work like `header` (from `Email::Simple`) does but returns the strings decoded, if possible. This would make querying existing headers a lot easier and `Email::MIME`'s interface a lot more complete and logical.

Thans for considering it.

**Comment by rjbs** [comment]
I probably will add it, but be aware that `header` already decodes headers, in Email::MIME.  This means that the same input into Simple and MIME may have different results for the same `header` call.  Unfortunately, this design decision was there when I got here. :(

**Comment by mbunkus** [comment]
Oh. I wasn't aware of that as `header` is not explicitely documented in `Email::MIME`. Thanks for pointing it out. It's unfortunate that its behavior is different between the two modules, but there's nothing to be done about it; I totally understand.

It would be good to have this documented, probably more important than having `header_str` (which could simply be an alias to `header` then, I guess).

**Comment by rjbs** [comment]
I've made a new release of Email::Simple with _raw_ versions of everything, and a trial release of a new Email::MIME, which adds more of the methods needed.  I'll make a stable release in a week or so.  Thanks for the motivation!
