### ISSUE TITLE
Failed to encode both Header and Body correctly

### ISSUE THREAD

**Issue by leetom** [rjbs/Email-MIME#29]
I used this to send email in HTML format, but failed to encode both Header and Body in utf8.

If I add `use utf8` directive, as I have utf8 string in the source code file, there would be an error: 

`Wide character in subroutine entry at /path/to/perls/perl-5.20.2/lib/site_perl/5.20.2/Email/MIME/Encodings.pm line 55.`

If I don't add `use utf8` directive, the Header string would be mis-encoded, since `substr`  in `Email::MIME::Encode::mime_encode` would split utf8 characters. The code is something like this: 

    use strict;
	use warnings;
	use Email::MIME;
	use feature 'say';
	# use utf8;  # if I don't use this, then header is encoded incorrectly
	#binmode(STDOUT, ':utf8');

	my $body = '你好';

	my $email = Email::MIME->create(
	  header_str => [
	    To      =>'email@email.com',
	    From    => 'sender@email.com',
	    Subject => '你好',
	  ],
	  body => $body,
	  attributes => {
	      content_type => 'text/html',
	      charset => 'UTF-8',
	      encoding => 'quoted-printable',
	  },
	);

	print $email->body();

**Comment by pali** [comment]
That is expected. Assigned value to `body =>` must be in octets, not in Unicode.

If you write
```
use utf8;
my $body = '你好';
````
then `$body` will be Unicode string and that cannot be passed into `body =>`.

But if you write `my $body = '你好';` (without `use utf8;`) then `$body` will be stored as octets and so you can pass it to `body =>`.

If you want to pass Unicode string into body of Email::MIME, then use body_str. Look at documentation of Email::MIME for differences between *_raw and *_str functions.

What you probably want in your example is:

```
use strict;
use warnings;
use Email::MIME;
use utf8;

my $body = '你好';

my $email = Email::MIME->create(
  header_str => [
    To      => 'email@email.com',
    From    => 'sender@email.com',
    Subject => '你好',
  ],
  body_str => $body,
  attributes => {
      content_type => 'text/html',
      charset => 'UTF-8',
      encoding => 'quoted-printable',
  },
);
```
And then print body as:
```
print $email->body();
```
or via body_str (which returns Unicode string) and then properly set :utf8 IO handle on STDOUT:
```
binmode(STDOUT, ':utf8');
print $email->body_str();
```

So I would say, this issue should be closed as it is not a bug, just incorrect usage.

**Comment by leetom** [comment]
@pali  I misunderstood this, thanks a lot!
