### ISSUE TITLE
invalid mbox file 

### ISSUE THREAD

**Issue by HansMeiser234** [rjbs/Email-MIME#33]
Hello,

i have an issue here and dont know to handle. I think i need an experts help. Is this the right place? My issue is this:
I use typical Mailserver postfix->procmail->dovecot(mbox)
By procmail i start a filter which uses a perl script to remove attachments.  I use this code to remove attachments: http://www.txoof.com/2011/12/stripping-mime-attachments-from-email.html#!/2011/12/stripping-mime-attachments-from-email.html

This works very well, but in some rare cases it creates an invalid mail in this way:

A single mail in a mbox-file starts with a line like this:
From root@example.com  Tue Nov 29 14:47:15 2016
This line is added by MTA and after that line follows content of email.

In some rare cases this line is broken (white space after 16:)
From example@example.com  Fri Nov 25 16: 18:08 2016

I cant explain that. Code seems to be ok and í cant find any line which looks suspicious. the only hint i have is that email::mime on this machine is quite old, version is 1.910-1

Is this a known issue in older version of email::mime? i hope so,  otherwise i would running out of ideas.
Do you have a clue for me?

Thanks,
Hans

**Comment by pali** [comment]
Email::MIME does not support and does not process/parse Mbox files. So this is not related to Email::MIME.
