### ISSUE TITLE
New content_type handling breaks Email::MIME::CreateHTML usage

### ISSUE THREAD

**Issue by lukec** [rjbs/Email-MIME#68]
Hey there - my projects' unit tests started failing due to the latest Email::MIME changes.

You can reproduce it with this snippet:

```
use Email::MIME;
use Email::MIME::CreateHTML;

Email::MIME->create_html(
    header => [
        To => 'luke@example.com',
        From => 'luke@example.com',
    ],
    body => 'Hello world',
    text_body => 'Hey world',
    text_body_attributes => {
        content_type => 'text/plain; charset=utf-8',
    }
);
```

This gives you this message:
`Invalid Content-Type 'subtype' parameter`

Prior to these recent changes, this code worked fine.

The problem seems to be related to this change: https://github.com/rjbs/Email-MIME/commit/e80d8a435dfe167a7883a6350f8c2dc4a8b5039f

I'm not sure what to propose as a fix.

**Comment by lukec** [comment]
Actually this is a simpler way to trigger it.  I copied this code out of `Email::MIME::CreateHTML`:

```
Email::MIME->create(
    attributes => {
        content_type => 'text/plain; charset=utf-8',
    },
    body => 'hello world',
);
```

**Comment by dxdc** [comment]
@lukec should it be this way?

```
attributes => {
        content_type => 'text/plain',
        charset => 'utf8'
    }
```

**Comment by lukec** [comment]
@dxdc Thank you very much! This change to my code appears to work!

You've solved the bug for me.  I'm not sure if I was doing it incorrectly before, or if that behaviour should be retained in the latest version.  

Please feel free to mark this as not a bug if you feel the behaviour I was depending on is not legit.

Thank you again @dxdc !

**Comment by dxdc** [comment]
@lukec I think you may not have been specifying it correctly before. I'm not a maintainer of this package, just an interested party :) Glad it works!
