### ISSUE TITLE
Documentation advises use of currently broken CPAN module Email::Stuffer

### ISSUE THREAD

**Issue by jkeenan** [rjbs/Email-MIME#69]
Email-MIME-1.949's documentation begins by advising the reader to use Email::Stuffer instead.
```
NAME
Email::MIME - easy MIME message handling

VERSION
version 1.949

SYNOPSIS
Wait! Before you read this, maybe you just need Email::Stuffer, which is a
much easier-to-use tool for building simple email messages that might have
attachments or both plain text and HTML. If that doesn't do it for you, then
by all means keep reading.

  use Email::MIME;
  my $parsed = Email::MIME->new($message);
```
However, it appears that the release of version 1.949 has broken Email::Stuffer's test suite.
See: https://github.com/rjbs/Email-Stuffer/issues/54.

(And this has also broken Email::Stuff.  https://rt.cpan.org/Ticket/Display.html?id=132721)

Thank you very much.
Jim Keenan

**Comment by mvz** [comment]
This appears to be fixed in the latest release of Email::Stuffer.
