### ISSUE TITLE
Email::MIME::body_set(): misleading documentation

### ISSUE THREAD

**Issue by jkeenan** [rjbs/Email-MIME#70]
The documentation for [Email::MIME::body_set](https://metacpan.org/pod/Email::MIME#body_set) states:
```
This method overrides the default body_set() method.
```
This is confusing.  Does one method called `body_set` override another method **also** named `body_set`?  That doesn't seem likely.

Can you investigate?

Thank you very much.
Jim Keenan

**Comment by mvz** [comment]
I think it means it overrides the `body_set` method from `Email::Simple`.

**Comment by rjbs** [comment]
I've removed this sentence, as it added no value.  Thanks.
