### ISSUE TITLE
Very slow regex can cause huge performance hit on large mime parts

### ISSUE THREAD

**Issue by ivulfson** [rjbs/Email-MIME#74]
```$self->SUPER::body_set(shift @bits) if ($bits[0] || '') !~ /.*:.*/;```

This regex is causing a huge slowdown when parsing large mime parts.
Changing to this makes it a lot faster:

```$self->SUPER::body_set(shift @bits) if ($bits[0] || '') !~ /:/;```

Better yet:

```$self->SUPER::body_set(shift @bits) if index(($bits[0] || ''), ':') == -1;```

**Comment by rjbs** [comment]
This was applied in 1ff002c83 in 2020.
